In [1]:
import pandas as pd
import numpy as np
from decimal import Decimal
import glob
import backtrader as bt
import matplotlib
import matplotlib.pyplot as plt
import pandas_ta as ta
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

# Ensure plots are rendered inline in the notebook
pio.renderers.default = "notebook"
matplotlib.use('Agg')
%matplotlib inline

In [2]:
# Define the path to your CSV files
file_path_pattern = '/root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_*.csv'

# Define the column names
column_names = ['DATE', 'TIME', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'TICKVOL', 'VOL', 'SPREAD']

# Load and combine all CSV files
all_files = glob.glob(file_path_pattern)
data_list = []

for file in all_files:
    print(f"Loading file: {file}")  # Debugging: Print file being loaded
    df = pd.read_csv(file, delimiter=',', names=column_names, header=None, dtype=str)
    # print(df.head())  # Debugging: Print the first few rows of the loaded DataFrame
    data_list.append(df)

combined_data = pd.concat(data_list)

# Check the combined data before parsing dates
print("Combined data before parsing dates:")
print(combined_data.head())

# Combine <DATE> and <TIME> into a single datetime column
combined_data['datetime'] = pd.to_datetime(combined_data['DATE'] + ' ' + combined_data['TIME'], format='%Y.%m.%d %H:%M', errors='coerce')

# Check the combined data after parsing dates
print("Combined data after parsing dates:")
print(combined_data.head())

# Check for rows with NaT in datetime column
print("Rows with NaT in datetime column:")
print(combined_data[combined_data['datetime'].isna()].head())

# Drop rows with NaT in datetime column
combined_data.dropna(subset=['datetime'], inplace=True)

# Set datetime as the index
combined_data.set_index('datetime', inplace=True)
combined_data.sort_index(inplace=True)

# Check the combined data before converting numeric columns
print("Combined data before converting numeric columns:")
print(combined_data.head())

# Convert numeric columns to appropriate data types
numeric_columns = ['OPEN', 'HIGH', 'LOW', 'CLOSE', 'TICKVOL', 'VOL', 'SPREAD']
combined_data[numeric_columns] = combined_data[numeric_columns].apply(pd.to_numeric, errors='coerce')

# Check the combined data after converting numeric columns
print("Combined data after converting numeric columns:")
print(combined_data.head())

# Drop rows with NaN values in numeric columns
combined_data.replace([np.inf, -np.inf], np.nan, inplace=True)
combined_data.fillna(0, inplace=True)

# Display the final combined data
print("Final combined data:")
combined_data.head()

Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2007.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2018.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2005.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2012.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2000.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2010.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2013.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2015.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2017.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2021.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2019.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2004.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2020.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2006.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_202301.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2014.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2002.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_202103311341_202302201425.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2022.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2016.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2011.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2001.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2003.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2008.csv
Loading file: /root/github/CTI_Scripts/py_scripts/backtesting/historical_data/EURUSD/DAT_MT_EURUSD_M1_2009.csv
Combined data before parsing dates:
         DATE   TIME      OPEN      HIGH       LOW     CLOSE TICKVOL  VOL  \
0  2007.01.01  20:00  1.323700  1.323700  1.323600  1.323700       0  NaN
1  2007.01.01  20:01  1.323600  1.323700  1.323600  1.323600       0  NaN
2  2007.01.01  20:02  1.323700  1.323800  1.323600  1.323600       0  NaN
3  2007.01.01  20:03  1.323700  1.323700  1.323600  1.323600       0  NaN
4  2007.01.01  20:04  1.323500  1.323600  1.323500  1.323500       0  NaN

  SPREAD
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Combined data after parsing dates:
         DATE   TIME      OPEN      HIGH       LOW     CLOSE TICKVOL  VOL  \
0  2007.01.01  20:00  1.323700  1.323700  1.323600  1.323700       0  NaN
1  2007.01.01  20:01  1.323600  1.323700  1.323600  1.323600       0  NaN
2  2007.01.01  20:02  1.323700  1.323800  1.323600  1.323600       0  NaN
3  2007.01.01  20:03  1.323700  1.323700  1.323600  1.323600       0  NaN
4  2007.01.01  20:04  1.323500  1.323600  1.323500  1.323500       0  NaN

  SPREAD            datetime
0    NaN 2007-01-01 20:00:00
1    NaN 2007-01-01 20:01:00
2    NaN 2007-01-01 20:02:00
3    NaN 2007-01-01 20:03:00
4    NaN 2007-01-01 20:04:00
Rows with NaT in datetime column:
                                                DATE TIME OPEN HIGH  LOW  \
0  2021.03.31\t13:41:00\t1.17292\t1.17312\t1.1729...  NaN  NaN  NaN  NaN
1  2021.03.31\t13:42:00\t1.17312\t1.17319\t1.1731...  NaN  NaN  NaN  NaN
2  2021.03.31\t13:43:00\t1.17314\t1.17318\t1.1730...  NaN  NaN  NaN  NaN
3  2021.03.31\t13:44:00\t1.17317\t1.17317\t1.1729...  NaN  NaN  NaN  NaN
4  2021.03.31\t13:45:00\t1.17302\t1.17317\t1.1730...  NaN  NaN  NaN  NaN

  CLOSE TICKVOL  VOL SPREAD datetime
0   NaN     NaN  NaN    NaN      NaT
1   NaN     NaN  NaN    NaN      NaT
2   NaN     NaN  NaN    NaN      NaT
3   NaN     NaN  NaN    NaN      NaT
4   NaN     NaN  NaN    NaN      NaT
Combined data before converting numeric columns:
                           DATE   TIME      OPEN      HIGH       LOW  \
datetime
2000-05-30 17:27:00  2000.05.30  17:27  0.930200  0.930200  0.930200
2000-05-30 17:35:00  2000.05.30  17:35  0.930400  0.930500  0.930400
2000-05-30 17:38:00  2000.05.30  17:38  0.930400  0.930400  0.930300
2000-05-30 17:43:00  2000.05.30  17:43  0.930100  0.930100  0.930000
2000-05-30 17:44:00  2000.05.30  17:44  0.929800  0.929800  0.929700

                        CLOSE TICKVOL  VOL SPREAD
datetime
2000-05-30 17:27:00  0.930200       0  NaN    NaN
2000-05-30 17:35:00  0.930500       0  NaN    NaN
2000-05-30 17:38:00  0.930300       0  NaN    NaN
2000-05-30 17:43:00  0.930000       0  NaN    NaN
2000-05-30 17:44:00  0.929700       0  NaN    NaN
Combined data after converting numeric columns:
                           DATE   TIME    OPEN    HIGH     LOW   CLOSE  \
datetime
2000-05-30 17:27:00  2000.05.30  17:27  0.9302  0.9302  0.9302  0.9302
2000-05-30 17:35:00  2000.05.30  17:35  0.9304  0.9305  0.9304  0.9305
2000-05-30 17:38:00  2000.05.30  17:38  0.9304  0.9304  0.9303  0.9303
2000-05-30 17:43:00  2000.05.30  17:43  0.9301  0.9301  0.9300  0.9300
2000-05-30 17:44:00  2000.05.30  17:44  0.9298  0.9298  0.9297  0.9297

                     TICKVOL  VOL  SPREAD
datetime
2000-05-30 17:27:00        0  NaN     NaN
2000-05-30 17:35:00        0  NaN     NaN
2000-05-30 17:38:00        0  NaN     NaN
2000-05-30 17:43:00        0  NaN     NaN
2000-05-30 17:44:00        0  NaN     NaN
Final combined data:

,DATE,TIME,OPEN,HIGH,LOW,CLOSE,TICKVOL,VOL,SPREAD
datetime,,,,,,,,,
2000-05-30 17:27:00,2000.05.30,17:27,0.9302,0.9302,0.9302,0.9302,0,0.0,0.0
2000-05-30 17:35:00,2000.05.30,17:35,0.9304,0.9305,0.9304,0.9305,0,0.0,0.0
2000-05-30 17:38:00,2000.05.30,17:38,0.9304,0.9304,0.9303,0.9303,0,0.0,0.0
2000-05-30 17:43:00,2000.05.30,17:43,0.9301,0.9301,0.9300,0.9300,0,0.0,0.0
2000-05-30 17:44:00,2000.05.30,17:44,0.9298,0.9298,0.9297,0.9297,0,0.0,0.0

In [3]:
combined_data_1m = combined_data

combined_data_1m = combined_data_1m.drop(columns=['DATE', 'TIME'])

combined_data_1m.head()

                       OPEN    HIGH     LOW   CLOSE  TICKVOL  VOL  SPREAD
datetime
2000-05-30 17:27:00  0.9302  0.9302  0.9302  0.9302        0  0.0     0.0
2000-05-30 17:35:00  0.9304  0.9305  0.9304  0.9305        0  0.0     0.0
2000-05-30 17:38:00  0.9304  0.9304  0.9303  0.9303        0  0.0     0.0
2000-05-30 17:43:00  0.9301  0.9301  0.9300  0.9300        0  0.0     0.0
2000-05-30 17:44:00  0.9298  0.9298  0.9297  0.9297        0  0.0     0.0

In [4]:
# Calculate indicators
aroon_length = 50
ema_length = 20
stoch_rsi_length = 14
stoch_rsi_smoothK = 3
stoch_rsi_smoothD = 3
supertrend_length = 50
supertrend_mult = 3.0
kc_length = 20
kc_scalar = 1.5
atr_length = 14

combined_data_1m['AROON-OSC'] = ta.aroon(
    combined_data_1m['HIGH'],
    combined_data_1m['LOW'],
    length=aroon_length
)[f'AROONOSC_{aroon_length}'].round(2)
combined_data_1m['EMA_50'] = ta.ema(combined_data_1m['CLOSE'], length=ema_length).round(5)
combined_data_1m['STOCH-RSId'] = ta.stochrsi(
    combined_data_1m['CLOSE'],
    length=stoch_rsi_length,
    smoothK=stoch_rsi_smoothK,
    smoothD=stoch_rsi_smoothD
)[f'STOCHRSId_{stoch_rsi_length}_{stoch_rsi_length}_{stoch_rsi_smoothK}_{stoch_rsi_smoothD}'].round(2)
combined_data_1m['STOCH-RSIk'] = ta.stochrsi(
    combined_data_1m['CLOSE'],
    length=stoch_rsi_length,
    smoothK=stoch_rsi_smoothK,
    smoothD=stoch_rsi_smoothD
)[f'STOCHRSIk_{stoch_rsi_length}_{stoch_rsi_length}_{stoch_rsi_smoothK}_{stoch_rsi_smoothD}'].round(2)
combined_data_1m['SUPERTREND'] = ta.supertrend(
    combined_data_1m['HIGH'],
    combined_data_1m['LOW'],
    combined_data_1m['CLOSE'],
    length=supertrend_length,
    multiplier=supertrend_mult
)[f'SUPERT_{supertrend_length}_{supertrend_mult}'].round(5)
combined_data_1m['Keltner-Upper'] = ta.kc(
    high=combined_data_1m['HIGH'],
    low=combined_data_1m['LOW'],
    close=combined_data_1m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCUe_{kc_length}_{kc_scalar}'].round(5)
combined_data_1m['Keltner-Basis'] = ta.kc(
    high=combined_data_1m['HIGH'],
    low=combined_data_1m['LOW'],
    close=combined_data_1m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCBe_{kc_length}_{kc_scalar}'].round(5)
combined_data_1m['Keltner-Lower'] = ta.kc(
    high=combined_data_1m['HIGH'],
    low=combined_data_1m['LOW'],
    close=combined_data_1m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCLe_{kc_length}_{kc_scalar}'].round(5)
combined_data_1m['ATR'] = ta.atr(
    high=combined_data_1m['HIGH'],
    low=combined_data_1m['LOW'],
    close=combined_data_1m['CLOSE'],
    length=atr_length
).round(5)



# Drop rows with NaN values (due to indicator calculation)
combined_data_1m.dropna(inplace=True)

# Display the data with indicators
print("Data with indicators:")
combined_data_1m.head()

Data with indicators:

,OPEN,HIGH,LOW,CLOSE,TICKVOL,VOL,SPREAD,AROON-OSC,EMA_50,STOCH-RSId,STOCH-RSIk,SUPERTREND,Keltner-Upper,Keltner-Basis,Keltner-Lower,ATR
datetime,,,,,,,,,,,,,,,,
2000-05-30 19:56:00,0.9297,0.9297,0.9297,0.9297,0,0.0,0.0,-78.0,0.92961,80.49,78.19,0.92930,0.92979,0.92961,0.92943,0.00012
2000-05-30 19:57:00,0.9296,0.9296,0.9295,0.9295,0,0.0,0.0,-78.0,0.92960,78.62,79.47,0.92930,0.92979,0.92960,0.92941,0.00013
2000-05-30 19:58:00,0.9297,0.9299,0.9297,0.9298,0,0.0,0.0,-76.0,0.92962,81.34,86.36,0.92938,0.92985,0.92962,0.92939,0.00015
2000-05-30 19:59:00,0.9299,0.9305,0.9299,0.9305,0,0.0,0.0,26.0,0.92970,84.07,86.36,0.92974,0.93001,0.92970,0.92939,0.00019
2000-05-30 20:00:00,0.9306,0.9307,0.9306,0.9307,0,0.0,0.0,28.0,0.92980,90.91,100.00,0.93019,0.93010,0.92980,0.92949,0.00019

In [64]:
plotly_data = combined_data_1m.loc['2021-01-01':'2021-01-31']

# Create a Plotly figure with subplots
fig = make_subplots(rows=4, cols=1, shared_xaxes=True, 
                    vertical_spacing=0.02, 
                    row_heights=[0.10, 0.75, 0.15, 0.15],
                    subplot_titles=('ATR 50',
                                    'EMA 50 | Supertrend 50, 3.0 | Keltner Channels 20, 1.5',
                                    'Aroon Oscillator 50',
                                    'Stochastic RSI 14, 3, 3'
                                )
                            )

# Add candlestick chart
fig.add_trace(go.Candlestick(x=plotly_data.index,
                             open=plotly_data['OPEN'],
                             high=plotly_data['HIGH'],
                             low=plotly_data['LOW'],
                             close=plotly_data['CLOSE'],
                             ),
            row=2, col=1)

# Add ATR to top of chart
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['ATR'],
    mode='lines',
    line=go.scatter.Line(color='yellow'),
    name='ATR'
), row=1, col=1)
# Add indicators to candlestick chart
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['EMA_50'],
    mode='lines',
    line=go.scatter.Line(color='red'),
    name='EMA 50'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['SUPERTREND'],
    mode='lines',
    line=go.scatter.Line(color='green'),
    name='SUPERTREND'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Upper'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Keltner-Upper'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Basis'],
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Keltner-Basis'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Lower'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Keltner-Lower'
), row=2, col=1)

# Add Aroon Oscillator
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['AROON-OSC'],
    mode='lines',
    line=go.scatter.Line(color='purple'),
    name='Aroon Oscillator'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[0] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='grey', dash='dash'),
    name='Aroon Osc Zero Line'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[60] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Aroon Osc Mid Line'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[-60] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Aroon Osc Upper Line'
), row=3, col=1)

# Add Stochastic RSI
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['STOCH-RSId'],
    mode='lines',
    line=go.scatter.Line(color='orange'),
    name='Stochastic RSI %D'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['STOCH-RSIk'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Stochastic RSI %K'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[20] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='red', dash='dash'),
    name='Oversold Threshold'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[80] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='green', dash='dash'),
    name='Overbought Threshold'
), row=4, col=1)


fig.update_layout(
    title='EURUSD 1m Candlestick Chart with Indicators January 2021',
    xaxis2=dict(
        rangeslider=dict(visible=False),
        rangebreaks=[
            dict(bounds=["sat", "mon"]),  # hide weekends
            dict(values=["2021-01-08 17:00", "2021-01-10 17:00"])
        ]
    ),
    yaxis=dict(title='Price', autorange=True),
    dragmode='zoom',
    uirevision='dynamic',
)

fig.write_html('./plotly/test_plot_EURUSD_1m.html')

In [5]:
combined_data_5m = combined_data.resample('5min').agg({
    'OPEN': 'first',
    'HIGH': 'max',
    'LOW': 'min',
    'CLOSE': 'last',
    'TICKVOL': 'sum',  # Aggregate tick volumes
    'VOL': 'sum',      # Aggregate actual volumes
    'SPREAD': 'mean',  # Average spread
}).dropna()

# Ensure datetime is set as the index
combined_data_5m.reset_index(inplace=True)  # Ensure 'datetime' is a column
combined_data_5m['datetime'] = pd.to_datetime(combined_data_5m['datetime'])  # Convert to datetime
combined_data_5m.set_index('datetime', inplace=True)  # Set as index

# Display the resampled data
combined_data_5m.head()

                       OPEN    HIGH     LOW   CLOSE  TICKVOL  VOL  SPREAD
datetime
2000-05-30 17:25:00  0.9302  0.9302  0.9302  0.9302        0  0.0     0.0
2000-05-30 17:35:00  0.9304  0.9305  0.9303  0.9303        0  0.0     0.0
2000-05-30 17:40:00  0.9301  0.9301  0.9297  0.9297        0  0.0     0.0
2000-05-30 18:25:00  0.9298  0.9299  0.9298  0.9299        0  0.0     0.0
2000-05-30 18:35:00  0.9300  0.9300  0.9300  0.9300        0  0.0     0.0

In [6]:
# Calculate indicators
aroon_length = 50
ema_length = 20
stoch_rsi_length = 14
stoch_rsi_smoothK = 3
stoch_rsi_smoothD = 3
supertrend_length = 50
supertrend_mult = 3.0
kc_length = 20
kc_scalar = 1.5
atr_length = 14

combined_data_5m['AROON-OSC'] = ta.aroon(
    combined_data_5m['HIGH'],
    combined_data_5m['LOW'],
    length=aroon_length
)[f'AROONOSC_{aroon_length}'].round(2)
combined_data_5m['EMA_50'] = ta.ema(combined_data_5m['CLOSE'], length=ema_length).round(5)
combined_data_5m['STOCH-RSId'] = ta.stochrsi(
    combined_data_5m['CLOSE'],
    length=stoch_rsi_length,
    smoothK=stoch_rsi_smoothK,
    smoothD=stoch_rsi_smoothD
)[f'STOCHRSId_{stoch_rsi_length}_{stoch_rsi_length}_{stoch_rsi_smoothK}_{stoch_rsi_smoothD}'].round(2)
combined_data_5m['STOCH-RSIk'] = ta.stochrsi(
    combined_data_5m['CLOSE'],
    length=stoch_rsi_length,
    smoothK=stoch_rsi_smoothK,
    smoothD=stoch_rsi_smoothD
)[f'STOCHRSIk_{stoch_rsi_length}_{stoch_rsi_length}_{stoch_rsi_smoothK}_{stoch_rsi_smoothD}'].round(2)
combined_data_5m['SUPERTREND'] = ta.supertrend(
    combined_data_5m['HIGH'],
    combined_data_5m['LOW'],
    combined_data_5m['CLOSE'],
    length=supertrend_length,
    multiplier=supertrend_mult
)[f'SUPERT_{supertrend_length}_{supertrend_mult}'].round(5)
combined_data_5m['Keltner-Upper'] = ta.kc(
    high=combined_data_5m['HIGH'],
    low=combined_data_5m['LOW'],
    close=combined_data_5m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCUe_{kc_length}_{kc_scalar}'].round(5)
combined_data_5m['Keltner-Basis'] = ta.kc(
    high=combined_data_5m['HIGH'],
    low=combined_data_5m['LOW'],
    close=combined_data_5m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCBe_{kc_length}_{kc_scalar}'].round(5)
combined_data_5m['Keltner-Lower'] = ta.kc(
    high=combined_data_5m['HIGH'],
    low=combined_data_5m['LOW'],
    close=combined_data_5m['CLOSE'],
    length=kc_length,
    scalar=kc_scalar
)[f'KCLe_{kc_length}_{kc_scalar}'].round(5)
combined_data_5m['ATR'] = ta.atr(
    high=combined_data_5m['HIGH'],
    low=combined_data_5m['LOW'],
    close=combined_data_5m['CLOSE'],
    length=atr_length
).round(5)


# Drop rows with NaN values (due to indicator calculation)
combined_data_5m.dropna(inplace=True)

# Display the data with indicators
print("5 min Data with indicators:")
combined_data_5m.head()

5 min Data with indicators:

,OPEN,HIGH,LOW,CLOSE,TICKVOL,VOL,SPREAD,AROON-OSC,EMA_50,STOCH-RSId,STOCH-RSIk,SUPERTREND,Keltner-Upper,Keltner-Basis,Keltner-Lower,ATR
datetime,,,,,,,,,,,,,,,,
2000-05-31 01:00:00,0.9318,0.9318,0.9318,0.9318,0,0.0,0.0,30.0,0.93155,35.15,40.78,0.93096,0.93189,0.93155,0.93121,0.00025
2000-05-31 01:05:00,0.9317,0.9319,0.9317,0.9319,0,0.0,0.0,30.0,0.93158,41.57,50.38,0.93096,0.93192,0.93158,0.93124,0.00024
2000-05-31 01:10:00,0.9321,0.9322,0.9321,0.9321,0,0.0,0.0,30.0,0.93163,50.26,59.60,0.93131,0.93198,0.93163,0.93128,0.00025
2000-05-31 01:15:00,0.9322,0.9322,0.9322,0.9322,0,0.0,0.0,30.0,0.93169,59.53,68.62,0.93137,0.93202,0.93169,0.93136,0.00024
2000-05-31 01:30:00,0.9317,0.9317,0.9317,0.9317,0,0.0,0.0,30.0,0.93169,62.62,59.63,0.93137,0.93206,0.93169,0.93132,0.00025

In [7]:
data_5m_2018 = combined_data_5m.loc['2018-01-01':'2018-12-31']

print(data_5m_2018.head())

matching_rows = data_5m_2018[data_5m_2018['CLOSE'] == data_5m_2018['SUPERTREND']]
print(f'Number of matching rows: {len(matching_rows)}')
matching_rows.head()

                        OPEN     HIGH      LOW    CLOSE  TICKVOL  VOL  SPREAD  \
datetime
2018-01-01 17:00:00  1.20037  1.20100  1.20017  1.20048        0  0.0     0.0
2018-01-01 17:05:00  1.20050  1.20097  1.20027  1.20094        0  0.0     0.0
2018-01-01 17:10:00  1.20094  1.20095  1.20076  1.20093        0  0.0     0.0
2018-01-01 17:15:00  1.20092  1.20105  1.20036  1.20050        0  0.0     0.0
2018-01-01 17:20:00  1.20053  1.20055  1.20044  1.20048        0  0.0     0.0

                     AROON-OSC   EMA_50  STOCH-RSId  STOCH-RSIk  SUPERTREND  \
datetime
2018-01-01 17:00:00      -92.0  1.20008       70.37       94.04     1.19961
2018-01-01 17:05:00      -92.0  1.20016       87.19      100.00     1.19962
2018-01-01 17:10:00      -92.0  1.20023       97.95       99.80     1.19986
2018-01-01 17:15:00      -86.0  1.20026       97.13       91.59     1.19986
2018-01-01 17:20:00      -86.0  1.20028       91.47       83.03     1.19986

                     Keltner-Upper  Keltner-Basis  Keltner-Lower      ATR
datetime
2018-01-01 17:00:00        1.20073        1.20008        1.19942  0.00039
2018-01-01 17:05:00        1.20085        1.20016        1.19947  0.00041
2018-01-01 17:10:00        1.20088        1.20023        1.19958  0.00040
2018-01-01 17:15:00        1.20095        1.20026        1.19957  0.00042
2018-01-01 17:20:00        1.20092        1.20028        1.19964  0.00040
Number of matching rows: 47

,OPEN,HIGH,LOW,CLOSE,TICKVOL,VOL,SPREAD,AROON-OSC,EMA_50,STOCH-RSId,STOCH-RSIk,SUPERTREND,Keltner-Upper,Keltner-Basis,Keltner-Lower,ATR
datetime,,,,,,,,,,,,,,,,
2018-01-02 00:40:00,1.20193,1.20206,1.20187,1.20206,0,0.0,0.0,-32.0,1.20173,99.09,99.98,1.20206,1.20196,1.20173,1.20150,0.00017
2018-01-18 04:05:00,1.21978,1.21997,1.21970,1.21970,0,0.0,0.0,26.0,1.22049,0.61,0.00,1.21970,1.22143,1.22049,1.21955,0.00063
2018-01-26 14:40:00,1.24245,1.24251,1.24176,1.24232,0,0.0,0.0,40.0,1.24339,17.41,12.26,1.24232,1.24460,1.24339,1.24218,0.00079
2018-01-31 11:00:00,1.24563,1.24631,1.24522,1.24529,0,0.0,0.0,34.0,1.24607,29.28,10.16,1.24529,1.24727,1.24607,1.24487,0.00076
2018-02-12 02:30:00,1.22861,1.22880,1.22780,1.22807,0,0.0,0.0,-62.0,1.22860,48.65,19.46,1.22807,1.22943,1.22860,1.22776,0.00053

In [63]:
plotly_data = combined_data_5m.loc['2021-01-01':'2021-01-31']

# Create a Plotly figure with subplots
fig = make_subplots(rows=4, cols=1, shared_xaxes=True, 
                    vertical_spacing=0.04, 
                    row_heights=[0.10, 0.75, 0.15, 0.15],
                    subplot_titles=(
                        'ATR 14',
                        'EMA 50 | Supertrend 50, 3.0 | Keltner Channels 20, 1.5',
                        'Aroon Oscillator 50',
                        'Stochastic RSI 14, 3, 3'
                    )
                )

# Add candlestick chart
fig.add_trace(go.Candlestick(x=plotly_data.index,
                             open=plotly_data['OPEN'],
                             high=plotly_data['HIGH'],
                             low=plotly_data['LOW'],
                             close=plotly_data['CLOSE'],
                             ),
            row=2, col=1)

# Add ATR to top of chart
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['ATR'],
    mode='lines',
    line=go.scatter.Line(color='yellow'),
    name='ATR'
), row=1, col=1)
# Add indicators to candlestick chart
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['EMA_50'],
    mode='lines',
    line=go.scatter.Line(color='red'),
    name='EMA 50'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['SUPERTREND'],
    mode='lines',
    line=go.scatter.Line(color='green'),
    name='SUPERTREND'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Upper'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Keltner-Upper'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Basis'],
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Keltner-Basis'
), row=2, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['Keltner-Lower'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Keltner-Lower'
), row=2, col=1)

# Add Aroon Oscillator
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['AROON-OSC'],
    mode='lines',
    line=go.scatter.Line(color='purple'),
    name='Aroon Oscillator'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[0] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='grey', dash='dash'),
    name='Aroon Osc Zero Line'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[60] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Aroon Osc Mid Line'
), row=3, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[-60] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='blue', dash='dash'),
    name='Aroon Osc Upper Line'
), row=3, col=1)

# Add Stochastic RSI
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['STOCH-RSId'],
    mode='lines',
    line=go.scatter.Line(color='orange'),
    name='Stochastic RSI %D'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=plotly_data['STOCH-RSIk'],
    mode='lines',
    line=go.scatter.Line(color='blue'),
    name='Stochastic RSI %K'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[20] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='red', dash='dash'),
    name='Oversold Threshold'
), row=4, col=1)
fig.add_trace(go.Scatter(
    x=plotly_data.index,
    y=[80] * len(plotly_data),
    mode='lines',
    line=go.scatter.Line(color='green', dash='dash'),
    name='Overbought Threshold'
), row=4, col=1)


fig.update_layout(
    title='EURUSD 5m Candlestick Chart with Indicators January 2021',
    xaxis2=dict(
        rangeslider=dict(visible=False),
        rangebreaks=[
            dict(bounds=["sat", "mon"]),  # hide weekends
            dict(values=["2021-01-08 17:00", "2021-01-10 17:00"])
        ]
    ),
    yaxis=dict(title='Price', autorange=True),
    dragmode='zoom',
    uirevision='dynamic',
)

fig.write_html('./plotly/test_plot_EURUSD_5m.html')

In [23]:
symbol = "EURUSD"
year = 2019
end_year = 2019

In [26]:
class SuperTrendStrategy(bt.Strategy):
    params = dict(
        risk_per_trade=0.0025,
        rr_ratio=2.8,
    )

    def __init__(self):
        self.buy_order = None
        self.sell_order = None
        self.trade_log = []
        self.open_trades = {}
        # self.data_1m = self.datas[0]
        # self.data_5m = self.datas[1]
        # Indicators
        self.supertrend = self.data.supertrend
        self.ema = self.data.ema_50
        self.aroon = self.data.aroon_osc
        self.stoch_rsi_d = self.data.stoch_rsi_d
        self.stoch_rsi_k = self.data.stoch_rsi_k
        self.kc_upper = self.data.keltner_upper
        self.kc_basis = self.data.keltner_basis
        self.kc_lower = self.data.keltner_lower
        self.atr = self.data.atr
        

    def log(self, *args, dt=None):
        '''Logging function for this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), ', '.join(map(str, args))))
    
    def calculate_take_profit(self, current_price, stop_loss, is_buy):
            if is_buy:
                return current_price + ((current_price - stop_loss) * self.params.rr_ratio)
            else:
                return current_price - ((stop_loss - current_price) * self.params.rr_ratio)

    def calculate_volume(self, current_price, stop_loss):
        # Calculate position size based on risk
        account_balance = self.broker.getvalue()
        risk_amount = account_balance * self.params.risk_per_trade
        stop_loss_distance = abs(current_price - stop_loss)

        # Ensure stop loss distance is not zero or too small
        if stop_loss_distance == 0:
            self.log("Skipping trade due to stop loss distance being 0")
            return None

        # Calculate volume in lots (1 lot = 100,000 units)
        volume = risk_amount / stop_loss_distance / 100000
        # if volume < 0:
        #     self.log(f"Skipping trade due to invalid volume - Volume: {volume}")
        #     return None
        # self.log(f"Calculated volume: {volume:.2f} lots")
        return round(volume, 2)           

    def next(self):
        if self.position:
            return
        
        # Fetch values
        current_price = self.data.close[0]
        current_high_range = self.data.high.get(size=5)
        current_low_range = self.data.low.get(size=5)
        recent_highs = self.data.high.get(size=10)
        recent_lows = self.data.low.get(size=10)

        if len(current_high_range) < 5 or len(current_low_range) < 5:
            self.log("Not enough data points to calculate current high and low.")
            return
        current_high = max(current_high_range)
        current_low = min(current_low_range)


        # Check if there are enough data points
        if len(recent_highs) < 10 or len(recent_lows) < 10:
            self.log("Not enough data points to calculate recent high and low.")
            return
        recent_high = max(recent_highs)
        recent_low = min(recent_lows)
        
        recent_high_index = self.data.high.get(size=10).index(recent_high)
        recent_low_index = self.data.low.get(size=10).index(recent_low)

        ago_recent_high = -(10 - recent_high_index)
        ago_recent_low = -(10 - recent_low_index)

        kc_upper_at_recent_high = self.kc_upper[ago_recent_high]
        kc_lower_at_recent_low = self.kc_lower[ago_recent_low]
        kc_basis = self.kc_basis[0]
        atr = self.atr[0]
        supertrend = self.supertrend[0]
        ema = self.ema[0]
        aroon = self.aroon[0]
        stoch_k = self.stoch_rsi_k[0]
        stoch_k_recent_max = max(self.stoch_rsi_k.get(size=5))
        stoch_k_recent_min = min(self.stoch_rsi_k.get(size=5))
        stoch_d = self.stoch_rsi_d[0]

        # Set Aroon Oscillator threshold
        aroon_threshold = 40

        # Log indicator values
        # print(f"Current Price: {current_price:.5f}, Supertrend: {supertrend:.5f}, EMA: {ema:.5f}, Aroon: {aroon:.2f}, Stoch K: {stoch_k:.2f}, Stoch D: {stoch_d:.2f}")

        # Calculate stop loss and take profit
        stop_loss = round(supertrend, 5)
        take_profit_buy = self.calculate_take_profit(current_price, stop_loss, is_buy=True)
        take_profit_sell = self.calculate_take_profit(current_price, stop_loss, is_buy=False)
        volume = self.calculate_volume(current_price, stop_loss)

        if volume is None or volume <= 0:
            self.log("Volume calculation resulted in None or non-positive value.")
            return
        
        
        # Long entry
        if (
            not self.buy_order 
            and not self.sell_order
            and current_price > supertrend 
            and current_price > ema
            and recent_high > kc_upper_at_recent_high
            and current_low <= kc_basis 
            and aroon > aroon_threshold 
            and stoch_k_recent_min < 30 
            and stoch_d < stoch_k
        ):
            main_order = self.buy(size=abs(volume), exectype=bt.Order.Market, transmit=False)
            stop_order = self.sell(
                size=abs(volume), exectype=bt.Order.Stop,
                price=stop_loss, parent=main_order, transmit=False
            )
            profit_order = self.sell(
                size=abs(volume), exectype=bt.Order.Limit,
                price=take_profit_buy, parent=main_order, transmit=True
            )
            self.buy_order = main_order

        # Short entry
        elif (
            not self.sell_order
            and not self.buy_order
            and current_price < supertrend 
            and current_price < ema 
            and recent_low < kc_lower_at_recent_low
            and current_high >= kc_basis
            and aroon < -aroon_threshold
            and stoch_k_recent_max > 70 
            and stoch_d > stoch_k
        ):
            main_order = self.sell(size=abs(volume), exectype=bt.Order.Market, transmit=False)
            stop_order = self.buy(
                size=abs(volume), exectype=bt.Order.Stop,
                price=stop_loss, parent=main_order, transmit=False
            )
            profit_order = self.buy(
                size=abs(volume), exectype=bt.Order.Limit,
                price=take_profit_sell, parent=main_order, transmit=True
            )
            self.sell_order = main_order

    def log_trade(self, trade_info):
        """Log a trade into the trade log."""
        self.trade_log.append(trade_info)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            return

        if order.status in [order.Completed]:
            if order.isbuy():
                self.log(f"BUY EXECUTED {order.ref} Price: \
{order.executed.price:.5f} \
Size: {order.executed.size:.2f}")
                self.buy_order = None  # Clear buy order
                self.open_trades[order.ref] = {
                    "TRADE NUMBER": len(self.trade_log) + 1,
                    "SYMBOL": "EURUSD",
                    "OPEN TIME": self.data.datetime.datetime(0),
                    "VOLUME": self.calculate_volume(self.data.close[0], self.supertrend[0]),
                    "SIDE": "BUY",
                    "OPEN PRICE": round(order.executed.price, 5),
                    "STOP LOSS": round(self.supertrend[0], 5),
                    "TAKE PROFIT": round(self.calculate_take_profit(self.data.close[0], self.supertrend[0], is_buy=True), 5),
                }
                self.log_trade(self.open_trades[order.ref])
            elif order.issell():
                self.log(f"SELL EXECUTED {order.ref} Price: {order.executed.price:.5f} Size: {order.executed.size:.2f}")
                self.sell_order = None  # Clear sell order
                self.open_trades[order.ref] = {
                    "TRADE NUMBER": len(self.trade_log) + 1,
                    "SYMBOL": "EURUSD",
                    "OPEN TIME": self.data.datetime.datetime(0),
                    "VOLUME": self.calculate_volume(self.data.close[0], self.supertrend[0]),
                    "SIDE": "SELL",
                    "OPEN PRICE": round(order.executed.price, 5),
                    "STOP LOSS": round(self.supertrend[0], 5),
                    "TAKE PROFIT": round(self.calculate_take_profit(self.data.close[0], self.supertrend[0], is_buy=False), 5),
                    "CLOSE TIME": None,
                    "CLOSE PRICE": None,
                    "PROFIT": None,
                    "RUNNING BALANCE": None,
                }
                self.log_trade(self.open_trades[order.ref])

            # Check if the order is closing an existing trade
            if order.exectype in [bt.Order.Stop, bt.Order.Limit] and order.parent:
                parent_ref = order.parent.ref
                if parent_ref in self.open_trades:
                    trade_info = self.open_trades.pop(parent_ref, {})
                    trade_info.update({
                        "CLOSE TIME": self.data.datetime.datetime(0),
                        "CLOSE PRICE": round(order.executed.price, 5),
                        "PROFIT": round(order.executed.pnl, 2),
                        "RUNNING BALANCE": round(self.broker.getvalue(), 2),
                    })
                    self.log_trade(trade_info)
                    self.log(f"TRADE CLOSED {parent_ref} by {order.ref}, Gross PnL={order.executed.pnl:.2f}")

            self.bar_executed = len(self)

        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.log(f'Order Canceled/Margin/Rejected: {order.ref}, Status: {order.getstatusname()}')
            if order.status == order.Margin:
                self.log(f"Margin call: Not enough margin for order {order.ref}")
            elif order.status == order.Rejected:
                self.log(f"Order rejected: {order.ref}")

        self.order = None

    # def notify_trade(self, trade):
    #     if not trade.isclosed:
    #         return

    #     self.log(f"TRADE CLOSED trade.myref={final_ref}, Gross PnL={trade.pnl:.2f}")

    #     trade_info = self.open_trades.pop(final_ref, {})
        
    #     trade_info.update({
    #         "CLOSE TIME": self.data.datetime.datetime(0),
    #         "CLOSE PRICE": round(trade.price, 5),
    #         "PROFIT": round(trade.pnl, 2),
    #         "RUNNING BALANCE": round(self.broker.getvalue(), 2),
    #     })
    #     self.log_trade(trade_info)

    def stop(self):
        # Save trades to a DataFrame at the end of the backtest
        self.trade_df = pd.DataFrame(self.trade_log)

        # Filter out canceled orders
        self.trade_df = self.trade_df[self.trade_df['CLOSE PRICE'].notna()]

        # Remove duplicates
        self.trade_df = self.trade_df.drop_duplicates()

        self.trade_df.to_csv(
            f'./back_test_data/{symbol}_{year}_5m_ST{supertrend_length}_EMA{ema_length}_\
AROON{aroon_length}.csv',
            index=False
        )

In [27]:
# Convert the pandas DataFrame to a Backtrader data feed
class PandasData(bt.feeds.PandasData):
    lines = (
        'ema_50',
        'stoch_rsi_k',
        'stoch_rsi_d',
        'supertrend',
        'aroon_osc',
        'keltner_upper',
        'keltner_basis',
        'keltner_lower',
        'atr',
    )
    params = (
        ('datetime', None),
        ('open', 'OPEN'),
        ('high', 'HIGH'),
        ('low', 'LOW'),
        ('close', 'CLOSE'),
        ('volume', 'VOL'),
        ('ema_50', 'EMA_50'),
        ('stoch_rsi_k', 'STOCH-RSIk'),
        ('stoch_rsi_d', 'STOCH-RSId'),
        ('supertrend', 'SUPERTREND'),
        ('aroon_osc', 'AROON-OSC'),
        ('keltner_upper', 'Keltner-Upper'),
        ('keltner_basis', 'Keltner-Basis'),
        ('keltner_lower', 'Keltner-Lower'),
        ('atr', 'ATR'),
    )

test_data_1m = combined_data_1m.loc[f'{year}-01-01':f'{end_year}-12-31']
test_data_5m = combined_data_5m.loc[f'{year}-01-01':f'{end_year}-12-31']

data_feed = PandasData(dataname=test_data_5m)

comm_info = bt.CommInfoBase(
    commission=0.02,
    leverage=30,
    margin=1 / 30,
    mult=100000
)

# Set up the Backtrader environment
cerebro = bt.Cerebro()
cerebro.addstrategy(SuperTrendStrategy)
cerebro.adddata(data_feed)
# cerebro.resampledata(data_feed, timeframe=bt.TimeFrame.Minutes, compression=5, name='5m')
cerebro.broker.set_cash(2500)
cerebro.broker.addcommissioninfo(comm_info)

# Run the backtest
cerebro.run(style='candlestick')
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
# print('Number of trades: %d' % len())
# print('Max Drawdown: %.2f' % cerebro.broker.getdrawdown().max.drawdown)
# Plot the results
# cerebro.plot(show=True)
# Dates to plot
# from_date = '2018-12-21'
# to_date = '2018-12-31'
# fig = cerebro.plot(
#     style='candelstick',
#     volume=False,
#     fromdate=pd.Timestamp(from_date),
#     todate=pd.Timestamp(to_date)
# )[0][0]
# fig.savefig('backtrader_plot_5m_2018_aroon24_ema50_st50.pdf', format='pdf', dpi=300)

2019-01-01, Not enough data points to calculate current high and low.
2019-01-01, Not enough data points to calculate current high and low.
2019-01-01, Not enough data points to calculate current high and low.
2019-01-01, Not enough data points to calculate current high and low.
2019-01-01, Not enough data points to calculate recent high and low.
2019-01-01, Not enough data points to calculate recent high and low.
2019-01-01, Not enough data points to calculate recent high and low.
2019-01-01, Not enough data points to calculate recent high and low.
2019-01-01, Not enough data points to calculate recent high and low.
2019-01-01, BUY EXECUTED 14667 Price: 1.14619 Size: 0.08
2019-01-01, SELL EXECUTED 14668 Price: 1.14538 Size: -0.08
2019-01-01, TRADE CLOSED 14667 by 14668, Gross PnL=-6.48
2019-01-01, Order Canceled/Margin/Rejected: 14669, Status: Canceled
2019-01-01, SELL EXECUTED 14670 Price: 1.14521 Size: -0.15
2019-01-02, BUY EXECUTED 14671 Price: 1.14562 Size: 0.15
2019-01-02, TRADE CLOSED 14670 by 14671, Gross PnL=-6.15
2019-01-02, Order Canceled/Margin/Rejected: 14672, Status: Canceled
2019-01-02, SELL EXECUTED 14673 Price: 1.14273 Size: -0.04
2019-01-02, BUY EXECUTED 14675 Price: 1.13786 Size: 0.04
2019-01-02, TRADE CLOSED 14673 by 14675, Gross PnL=19.49
2019-01-02, Order Canceled/Margin/Rejected: 14674, Status: Canceled
2019-01-02, SELL EXECUTED 14676 Price: 1.13572 Size: -0.04
2019-01-03, BUY EXECUTED 14677 Price: 1.13744 Size: 0.04
2019-01-03, TRADE CLOSED 14676 by 14677, Gross PnL=-6.88
2019-01-03, Order Canceled/Margin/Rejected: 14678, Status: Canceled
2019-01-03, SELL EXECUTED 14679 Price: 1.13485 Size: -0.06
2019-01-03, BUY EXECUTED 14680 Price: 1.13595 Size: 0.06
2019-01-03, TRADE CLOSED 14679 by 14680, Gross PnL=-6.60
2019-01-03, Order Canceled/Margin/Rejected: 14681, Status: Canceled
2019-01-03, BUY EXECUTED 14682 Price: 1.13961 Size: 0.02
2019-01-04, SELL EXECUTED 14683 Price: 1.13634 Size: -0.02
2019-01-04, TRADE CLOSED 14682 by 14683, Gross PnL=-6.54
2019-01-04, Order Canceled/Margin/Rejected: 14684, Status: Canceled
2019-01-06, BUY EXECUTED 14685 Price: 1.14103 Size: 0.06
2019-01-07, SELL EXECUTED 14687 Price: 1.14403 Size: -0.06
2019-01-07, TRADE CLOSED 14685 by 14687, Gross PnL=17.98
2019-01-07, Order Canceled/Margin/Rejected: 14686, Status: Canceled
2019-01-07, BUY EXECUTED 14688 Price: 1.14412 Size: 0.05
2019-01-07, SELL EXECUTED 14690 Price: 1.14797 Size: -0.05
2019-01-07, TRADE CLOSED 14688 by 14690, Gross PnL=19.23
2019-01-07, Order Canceled/Margin/Rejected: 14689, Status: Canceled
2019-01-07, BUY EXECUTED 14691 Price: 1.14795 Size: 0.05
2019-01-07, SELL EXECUTED 14692 Price: 1.14659 Size: -0.05
2019-01-07, TRADE CLOSED 14691 by 14692, Gross PnL=-6.80
2019-01-07, Order Canceled/Margin/Rejected: 14693, Status: Canceled
2019-01-07, SELL EXECUTED 14694 Price: 1.14405 Size: -0.05
2019-01-08, BUY EXECUTED 14695 Price: 1.14527 Size: 0.05
2019-01-08, TRADE CLOSED 14694 by 14695, Gross PnL=-6.10
2019-01-08, Order Canceled/Margin/Rejected: 14696, Status: Canceled
2019-01-08, SELL EXECUTED 14697 Price: 1.14331 Size: -0.07
2019-01-08, BUY EXECUTED 14698 Price: 1.14417 Size: 0.07
2019-01-08, TRADE CLOSED 14697 by 14698, Gross PnL=-6.02
2019-01-08, Order Canceled/Margin/Rejected: 14699, Status: Canceled
2019-01-08, SELL EXECUTED 14700 Price: 1.14297 Size: -0.05
2019-01-08, BUY EXECUTED 14701 Price: 1.14417 Size: 0.05
2019-01-08, TRADE CLOSED 14700 by 14701, Gross PnL=-6.00
2019-01-08, Order Canceled/Margin/Rejected: 14702, Status: Canceled
2019-01-08, BUY EXECUTED 14703 Price: 1.14527 Size: 0.04
2019-01-08, SELL EXECUTED 14704 Price: 1.14365 Size: -0.04
2019-01-08, TRADE CLOSED 14703 by 14704, Gross PnL=-6.48
2019-01-08, Order Canceled/Margin/Rejected: 14705, Status: Canceled
2019-01-08, SELL EXECUTED 14706 Price: 1.14402 Size: -0.07
2019-01-08, BUY EXECUTED 14707 Price: 1.14489 Size: 0.07
2019-01-08, TRADE CLOSED 14706 by 14707, Gross PnL=-6.09
2019-01-08, Order Canceled/Margin/Rejected: 14708, Status: Canceled
2019-01-08, BUY EXECUTED 14709 Price: 1.14622 Size: 0.06
2019-01-08, SELL EXECUTED 14710 Price: 1.14514 Size: -0.06
2019-01-08, TRADE CLOSED 14709 by 14710, Gross PnL=-6.48
2019-01-08, Order Canceled/Margin/Rejected: 14711, Status: Canceled
2019-01-09, BUY EXECUTED 14712 Price: 1.14629 Size: 0.07
2019-01-09, SELL EXECUTED 14713 Price: 1.14542 Size: -0.07
2019-01-09, TRADE CLOSED 14712 by 14713, Gross PnL=-6.09
2019-01-09, Order Canceled/Margin/Rejected: 14714, Status: Canceled
2019-01-09, BUY EXECUTED 14715 Price: 1.15361 Size: 0.03
2019-01-10, SELL EXECUTED 14716 Price: 1.15127 Size: -0.03
2019-01-10, TRADE CLOSED 14715 by 14716, Gross PnL=-7.02
2019-01-10, Order Canceled/Margin/Rejected: 14717, Status: Canceled
2019-01-10, SELL EXECUTED 14718 Price: 1.15122 Size: -0.03
2019-01-11, BUY EXECUTED 14719 Price: 1.15326 Size: 0.03
2019-01-11, TRADE CLOSED 14718 by 14719, Gross PnL=-6.12
2019-01-11, Order Canceled/Margin/Rejected: 14720, Status: Canceled
2019-01-11, SELL EXECUTED 14721 Price: 1.14774 Size: -0.14
2019-01-11, BUY EXECUTED 14723 Price: 1.14647 Size: 0.14
2019-01-11, TRADE CLOSED 14721 by 14723, Gross PnL=17.78
2019-01-11, Order Canceled/Margin/Rejected: 14722, Status: Canceled
2019-01-11, SELL EXECUTED 14724 Price: 1.14626 Size: -0.06
2019-01-13, BUY EXECUTED 14725 Price: 1.14734 Size: 0.06
2019-01-13, TRADE CLOSED 14724 by 14725, Gross PnL=-6.48
2019-01-13, Order Canceled/Margin/Rejected: 14726, Status: Canceled
2019-01-14, SELL EXECUTED 14727 Price: 1.14587 Size: -0.08
2019-01-14, BUY EXECUTED 14728 Price: 1.14662 Size: 0.08
2019-01-14, TRADE CLOSED 14727 by 14728, Gross PnL=-6.00
2019-01-14, Order Canceled/Margin/Rejected: 14729, Status: Canceled
2019-01-14, SELL EXECUTED 14730 Price: 1.14583 Size: -0.03
2019-01-14, BUY EXECUTED 14731 Price: 1.14785 Size: 0.03
2019-01-14, TRADE CLOSED 14730 by 14731, Gross PnL=-6.06
2019-01-14, Order Canceled/Margin/Rejected: 14732, Status: Canceled
2019-01-14, Skipping trade due to stop loss distance being 0
2019-01-14, Volume calculation resulted in None or non-positive value.
2019-01-14, BUY EXECUTED 14733 Price: 1.14755 Size: 0.09
2019-01-15, SELL EXECUTED 14734 Price: 1.14688 Size: -0.09
2019-01-15, TRADE CLOSED 14733 by 14734, Gross PnL=-6.03
2019-01-15, Order Canceled/Margin/Rejected: 14735, Status: Canceled
2019-01-15, SELL EXECUTED 14736 Price: 1.14315 Size: -0.08
2019-01-15, BUY EXECUTED 14737 Price: 1.14393 Size: 0.08
2019-01-15, TRADE CLOSED 14736 by 14737, Gross PnL=-6.24
2019-01-15, Order Canceled/Margin/Rejected: 14738, Status: Canceled
2019-01-15, SELL EXECUTED 14739 Price: 1.13898 Size: -0.05
2019-01-15, BUY EXECUTED 14740 Price: 1.14015 Size: 0.05
2019-01-15, TRADE CLOSED 14739 by 14740, Gross PnL=-5.85
2019-01-15, Order Canceled/Margin/Rejected: 14741, Status: Canceled
2019-01-15, BUY EXECUTED 14742 Price: 1.14150 Size: 0.03
2019-01-15, SELL EXECUTED 14743 Price: 1.13971 Size: -0.03
2019-01-15, TRADE CLOSED 14742 by 14743, Gross PnL=-5.37
2019-01-15, Order Canceled/Margin/Rejected: 14744, Status: Canceled
2019-01-15, SELL EXECUTED 14745 Price: 1.14014 Size: -0.09
2019-01-15, BUY EXECUTED 14746 Price: 1.14080 Size: 0.09
2019-01-15, TRADE CLOSED 14745 by 14746, Gross PnL=-5.94
2019-01-15, Order Canceled/Margin/Rejected: 14747, Status: Canceled
2019-01-16, BUY EXECUTED 14748 Price: 1.14097 Size: 0.13
2019-01-16, SELL EXECUTED 14749 Price: 1.14048 Size: -0.13
2019-01-16, TRADE CLOSED 14748 by 14749, Gross PnL=-6.37
2019-01-16, Order Canceled/Margin/Rejected: 14750, Status: Canceled
2019-01-16, BUY EXECUTED 14751 Price: 1.14072 Size: 0.05
2019-01-16, SELL EXECUTED 14752 Price: 1.13944 Size: -0.05
2019-01-16, TRADE CLOSED 14751 by 14752, Gross PnL=-6.40
2019-01-16, Order Canceled/Margin/Rejected: 14753, Status: Canceled
2019-01-16, SELL EXECUTED 14754 Price: 1.13958 Size: -0.13
2019-01-16, BUY EXECUTED 14756 Price: 1.13827 Size: 0.13
2019-01-16, TRADE CLOSED 14754 by 14756, Gross PnL=16.98
2019-01-16, Order Canceled/Margin/Rejected: 14755, Status: Canceled
2019-01-17, BUY EXECUTED 14757 Price: 1.13880 Size: 0.12
2019-01-17, SELL EXECUTED 14758 Price: 1.13821 Size: -0.12
2019-01-17, TRADE CLOSED 14757 by 14758, Gross PnL=-7.08
2019-01-17, Order Canceled/Margin/Rejected: 14759, Status: Canceled
2019-01-17, BUY EXECUTED 14760 Price: 1.13948 Size: 0.14
2019-01-17, SELL EXECUTED 14761 Price: 1.13895 Size: -0.14
2019-01-17, TRADE CLOSED 14760 by 14761, Gross PnL=-7.42
2019-01-17, Order Canceled/Margin/Rejected: 14762, Status: Canceled
2019-01-17, BUY EXECUTED 14763 Price: 1.14002 Size: 0.09
2019-01-17, SELL EXECUTED 14764 Price: 1.13931 Size: -0.09
2019-01-17, TRADE CLOSED 14763 by 14764, Gross PnL=-6.39
2019-01-17, Order Canceled/Margin/Rejected: 14765, Status: Canceled
2019-01-17, SELL EXECUTED 14766 Price: 1.13762 Size: -0.03
2019-01-17, BUY EXECUTED 14767 Price: 1.13947 Size: 0.03
2019-01-17, TRADE CLOSED 14766 by 14767, Gross PnL=-5.55
2019-01-17, Order Canceled/Margin/Rejected: 14768, Status: Canceled
2019-01-17, BUY EXECUTED 14769 Price: 1.13909 Size: 0.08
2019-01-18, SELL EXECUTED 14770 Price: 1.13833 Size: -0.08
2019-01-18, TRADE CLOSED 14769 by 14770, Gross PnL=-6.08
2019-01-18, Order Canceled/Margin/Rejected: 14771, Status: Canceled
2019-01-18, SELL EXECUTED 14772 Price: 1.13640 Size: -0.05
2019-01-20, BUY EXECUTED 14773 Price: 1.13763 Size: 0.05
2019-01-20, TRADE CLOSED 14772 by 14773, Gross PnL=-6.15
2019-01-20, Order Canceled/Margin/Rejected: 14774, Status: Canceled
2019-01-20, BUY EXECUTED 14775 Price: 1.13768 Size: 0.07
2019-01-21, SELL EXECUTED 14776 Price: 1.13681 Size: -0.07
2019-01-21, TRADE CLOSED 14775 by 14776, Gross PnL=-6.09
2019-01-21, Order Canceled/Margin/Rejected: 14777, Status: Canceled
2019-01-21, BUY EXECUTED 14778 Price: 1.13690 Size: 0.12
2019-01-21, SELL EXECUTED 14779 Price: 1.13638 Size: -0.12
2019-01-21, TRADE CLOSED 14778 by 14779, Gross PnL=-6.24
2019-01-21, Order Canceled/Margin/Rejected: 14780, Status: Canceled
2019-01-21, BUY EXECUTED 14781 Price: 1.13707 Size: 0.11
2019-01-21, SELL EXECUTED 14782 Price: 1.13654 Size: -0.11
2019-01-21, TRADE CLOSED 14781 by 14782, Gross PnL=-5.83
2019-01-21, Order Canceled/Margin/Rejected: 14783, Status: Canceled
2019-01-21, SELL EXECUTED 14784 Price: 1.13622 Size: -0.08
2019-01-22, BUY EXECUTED 14786 Price: 1.13415 Size: 0.08
2019-01-22, TRADE CLOSED 14784 by 14786, Gross PnL=16.58
2019-01-22, Order Canceled/Margin/Rejected: 14785, Status: Canceled
2019-01-22, BUY EXECUTED 14787 Price: 1.13591 Size: 0.10
2019-01-22, SELL EXECUTED 14788 Price: 1.13530 Size: -0.10
2019-01-22, TRADE CLOSED 14787 by 14788, Gross PnL=-6.10
2019-01-22, Order Canceled/Margin/Rejected: 14789, Status: Canceled
2019-01-22, SELL EXECUTED 14790 Price: 1.13601 Size: -0.13
2019-01-22, BUY EXECUTED 14791 Price: 1.13647 Size: 0.13
2019-01-22, TRADE CLOSED 14790 by 14791, Gross PnL=-5.98
2019-01-22, Order Canceled/Margin/Rejected: 14792, Status: Canceled
2019-01-22, BUY EXECUTED 14793 Price: 1.13662 Size: 0.08
2019-01-23, SELL EXECUTED 14794 Price: 1.13583 Size: -0.08
2019-01-23, TRADE CLOSED 14793 by 14794, Gross PnL=-6.32
2019-01-23, Order Canceled/Margin/Rejected: 14795, Status: Canceled
2019-01-23, BUY EXECUTED 14796 Price: 1.13689 Size: 0.06
2019-01-23, SELL EXECUTED 14797 Price: 1.13593 Size: -0.06
2019-01-23, TRADE CLOSED 14796 by 14797, Gross PnL=-5.76
2019-01-23, Order Canceled/Margin/Rejected: 14798, Status: Canceled
2019-01-23, BUY EXECUTED 14799 Price: 1.13931 Size: 0.05
2019-01-23, SELL EXECUTED 14800 Price: 1.13808 Size: -0.05
2019-01-23, TRADE CLOSED 14799 by 14800, Gross PnL=-6.15
2019-01-23, Order Canceled/Margin/Rejected: 14801, Status: Canceled
2019-01-23, SELL EXECUTED 14802 Price: 1.13814 Size: -0.09
2019-01-23, BUY EXECUTED 14803 Price: 1.13878 Size: 0.09
2019-01-23, TRADE CLOSED 14802 by 14803, Gross PnL=-5.76
2019-01-23, Order Canceled/Margin/Rejected: 14804, Status: Canceled
2019-01-23, BUY EXECUTED 14805 Price: 1.13874 Size: 0.09
2019-01-24, SELL EXECUTED 14806 Price: 1.13811 Size: -0.09
2019-01-24, TRADE CLOSED 14805 by 14806, Gross PnL=-5.67
2019-01-24, Order Canceled/Margin/Rejected: 14807, Status: Canceled
2019-01-24, SELL EXECUTED 14808 Price: 1.13812 Size: -0.08
2019-01-24, BUY EXECUTED 14810 Price: 1.13608 Size: 0.08
2019-01-24, TRADE CLOSED 14808 by 14810, Gross PnL=16.35
2019-01-24, Order Canceled/Margin/Rejected: 14809, Status: Canceled
2019-01-24, SELL EXECUTED 14811 Price: 1.13567 Size: -0.05
2019-01-24, BUY EXECUTED 14813 Price: 1.13239 Size: 0.05
2019-01-24, TRADE CLOSED 14811 by 14813, Gross PnL=16.38
2019-01-24, Order Canceled/Margin/Rejected: 14812, Status: Canceled
2019-01-24, SELL EXECUTED 14814 Price: 1.13003 Size: -0.04
2019-01-24, BUY EXECUTED 14815 Price: 1.13161 Size: 0.04
2019-01-24, TRADE CLOSED 14814 by 14815, Gross PnL=-6.32
2019-01-24, Order Canceled/Margin/Rejected: 14816, Status: Canceled
2019-01-24, BUY EXECUTED 14817 Price: 1.13212 Size: 0.10
2019-01-25, SELL EXECUTED 14818 Price: 1.13155 Size: -0.10
2019-01-25, TRADE CLOSED 14817 by 14818, Gross PnL=-5.70
2019-01-25, Order Canceled/Margin/Rejected: 14819, Status: Canceled
2019-01-25, BUY EXECUTED 14820 Price: 1.13459 Size: 0.06
2019-01-25, SELL EXECUTED 14822 Price: 1.13719 Size: -0.06
2019-01-25, TRADE CLOSED 14820 by 14822, Gross PnL=15.62
2019-01-25, Order Canceled/Margin/Rejected: 14821, Status: Canceled
2019-01-25, BUY EXECUTED 14823 Price: 1.14029 Size: 0.04
2019-01-28, SELL EXECUTED 14825 Price: 1.14406 Size: -0.04
2019-01-28, TRADE CLOSED 14823 by 14825, Gross PnL=15.09
2019-01-28, Order Canceled/Margin/Rejected: 14824, Status: Canceled
2019-01-28, BUY EXECUTED 14826 Price: 1.14348 Size: 0.11
2019-01-28, SELL EXECUTED 14827 Price: 1.14293 Size: -0.11
2019-01-28, TRADE CLOSED 14826 by 14827, Gross PnL=-6.05
2019-01-28, Order Canceled/Margin/Rejected: 14828, Status: Canceled
2019-01-28, SELL EXECUTED 14829 Price: 1.14275 Size: -0.08
2019-01-29, BUY EXECUTED 14830 Price: 1.14355 Size: 0.08
2019-01-29, TRADE CLOSED 14829 by 14830, Gross PnL=-6.40
2019-01-29, Order Canceled/Margin/Rejected: 14831, Status: Canceled
2019-01-29, BUY EXECUTED 14832 Price: 1.14356 Size: 0.10
2019-01-29, SELL EXECUTED 14833 Price: 1.14296 Size: -0.10
2019-01-29, TRADE CLOSED 14832 by 14833, Gross PnL=-6.00
2019-01-29, Order Canceled/Margin/Rejected: 14834, Status: Canceled
2019-01-29, SELL EXECUTED 14835 Price: 1.14324 Size: -0.09
2019-01-29, BUY EXECUTED 14837 Price: 1.14139 Size: 0.09
2019-01-29, TRADE CLOSED 14835 by 14837, Gross PnL=16.63
2019-01-29, Order Canceled/Margin/Rejected: 14836, Status: Canceled
2019-01-29, BUY EXECUTED 14838 Price: 1.14358 Size: 0.09
2019-01-30, SELL EXECUTED 14839 Price: 1.14287 Size: -0.09
2019-01-30, TRADE CLOSED 14838 by 14839, Gross PnL=-6.39
2019-01-30, Order Canceled/Margin/Rejected: 14840, Status: Canceled
2019-01-30, SELL EXECUTED 14841 Price: 1.14236 Size: -0.06
2019-01-30, BUY EXECUTED 14842 Price: 1.14344 Size: 0.06
2019-01-30, TRADE CLOSED 14841 by 14842, Gross PnL=-6.48
2019-01-30, Order Canceled/Margin/Rejected: 14843, Status: Canceled
2019-01-30, SELL EXECUTED 14844 Price: 1.14124 Size: -0.07
2019-01-30, BUY EXECUTED 14845 Price: 1.14213 Size: 0.07
2019-01-30, TRADE CLOSED 14844 by 14845, Gross PnL=-6.23
2019-01-30, Order Canceled/Margin/Rejected: 14846, Status: Canceled
2019-01-30, BUY EXECUTED 14847 Price: 1.14678 Size: 0.02
2019-02-04, SELL EXECUTED 14848 Price: 1.14299 Size: -0.02
2019-02-04, TRADE CLOSED 14847 by 14848, Gross PnL=-7.58
2019-02-04, Order Canceled/Margin/Rejected: 14849, Status: Canceled
2019-02-04, Skipping trade due to stop loss distance being 0
2019-02-04, Volume calculation resulted in None or non-positive value.
2019-02-04, BUY EXECUTED 14850 Price: 1.14383 Size: 0.09
2019-02-04, SELL EXECUTED 14851 Price: 1.14314 Size: -0.09
2019-02-04, TRADE CLOSED 14850 by 14851, Gross PnL=-6.21
2019-02-04, Order Canceled/Margin/Rejected: 14852, Status: Canceled
2019-02-05, SELL EXECUTED 14853 Price: 1.14315 Size: -0.14
2019-02-05, BUY EXECUTED 14855 Price: 1.14195 Size: 0.14
2019-02-05, TRADE CLOSED 14853 by 14855, Gross PnL=16.86
2019-02-05, Order Canceled/Margin/Rejected: 14854, Status: Canceled
2019-02-05, SELL EXECUTED 14856 Price: 1.14167 Size: -0.07
2019-02-05, BUY EXECUTED 14857 Price: 1.14247 Size: 0.07
2019-02-05, TRADE CLOSED 14856 by 14857, Gross PnL=-5.60
2019-02-05, Order Canceled/Margin/Rejected: 14858, Status: Canceled
2019-02-05, BUY EXECUTED 14859 Price: 1.14293 Size: 0.06
2019-02-05, SELL EXECUTED 14860 Price: 1.14189 Size: -0.06
2019-02-05, TRADE CLOSED 14859 by 14860, Gross PnL=-6.24
2019-02-05, Order Canceled/Margin/Rejected: 14861, Status: Canceled
2019-02-05, SELL EXECUTED 14862 Price: 1.14024 Size: -0.04
2019-02-05, BUY EXECUTED 14863 Price: 1.14156 Size: 0.04
2019-02-05, TRADE CLOSED 14862 by 14863, Gross PnL=-5.28
2019-02-05, Order Canceled/Margin/Rejected: 14864, Status: Canceled
2019-02-05, SELL EXECUTED 14865 Price: 1.14040 Size: -0.10
2019-02-06, BUY EXECUTED 14867 Price: 1.13878 Size: 0.10
2019-02-06, TRADE CLOSED 14865 by 14867, Gross PnL=16.24
2019-02-06, Order Canceled/Margin/Rejected: 14866, Status: Canceled
2019-02-06, SELL EXECUTED 14868 Price: 1.13847 Size: -0.13
2019-02-06, BUY EXECUTED 14869 Price: 1.13893 Size: 0.13
2019-02-06, TRADE CLOSED 14868 by 14869, Gross PnL=-5.98
2019-02-06, Order Canceled/Margin/Rejected: 14870, Status: Canceled
2019-02-06, SELL EXECUTED 14871 Price: 1.13823 Size: -0.08
2019-02-06, BUY EXECUTED 14873 Price: 1.13606 Size: 0.08
2019-02-06, TRADE CLOSED 14871 by 14873, Gross PnL=17.33
2019-02-06, Order Canceled/Margin/Rejected: 14872, Status: Canceled
2019-02-06, SELL EXECUTED 14874 Price: 1.13607 Size: -0.17
2019-02-07, BUY EXECUTED 14875 Price: 1.13643 Size: 0.17
2019-02-07, TRADE CLOSED 14874 by 14875, Gross PnL=-6.12
2019-02-07, Order Canceled/Margin/Rejected: 14876, Status: Canceled
2019-02-07, SELL EXECUTED 14877 Price: 1.13450 Size: -0.05
2019-02-07, BUY EXECUTED 14878 Price: 1.13571 Size: 0.05
2019-02-07, TRADE CLOSED 14877 by 14878, Gross PnL=-6.05
2019-02-07, Order Canceled/Margin/Rejected: 14879, Status: Canceled
2019-02-07, BUY EXECUTED 14880 Price: 1.13577 Size: 0.05
2019-02-07, SELL EXECUTED 14881 Price: 1.13463 Size: -0.05
2019-02-07, TRADE CLOSED 14880 by 14881, Gross PnL=-5.70
2019-02-07, Order Canceled/Margin/Rejected: 14882, Status: Canceled
2019-02-07, SELL EXECUTED 14883 Price: 1.13403 Size: -0.11
2019-02-08, BUY EXECUTED 14885 Price: 1.13254 Size: 0.11
2019-02-08, TRADE CLOSED 14883 by 14885, Gross PnL=16.43
2019-02-08, Order Canceled/Margin/Rejected: 14884, Status: Canceled
2019-02-08, BUY EXECUTED 14886 Price: 1.13418 Size: 0.09
2019-02-08, SELL EXECUTED 14887 Price: 1.13350 Size: -0.09
2019-02-08, TRADE CLOSED 14886 by 14887, Gross PnL=-6.12
2019-02-08, Order Canceled/Margin/Rejected: 14888, Status: Canceled
2019-02-08, SELL EXECUTED 14889 Price: 1.13258 Size: -0.07
2019-02-11, BUY EXECUTED 14891 Price: 1.13034 Size: 0.07
2019-02-11, TRADE CLOSED 14889 by 14891, Gross PnL=15.68
2019-02-11, Order Canceled/Margin/Rejected: 14890, Status: Canceled
2019-02-11, SELL EXECUTED 14892 Price: 1.13026 Size: -0.06
2019-02-11, BUY EXECUTED 14893 Price: 1.13127 Size: 0.06
2019-02-11, TRADE CLOSED 14892 by 14893, Gross PnL=-6.06
2019-02-11, Order Canceled/Margin/Rejected: 14894, Status: Canceled
2019-02-11, SELL EXECUTED 14895 Price: 1.12834 Size: -0.03
2019-02-12, BUY EXECUTED 14896 Price: 1.13009 Size: 0.03
2019-02-12, TRADE CLOSED 14895 by 14896, Gross PnL=-5.25
2019-02-12, Order Canceled/Margin/Rejected: 14897, Status: Canceled
2019-02-12, BUY EXECUTED 14898 Price: 1.12974 Size: 0.09
2019-02-12, SELL EXECUTED 14899 Price: 1.12909 Size: -0.09
2019-02-12, TRADE CLOSED 14898 by 14899, Gross PnL=-5.85
2019-02-12, Order Canceled/Margin/Rejected: 14900, Status: Canceled
2019-02-12, BUY EXECUTED 14901 Price: 1.12986 Size: 0.05
2019-02-12, SELL EXECUTED 14903 Price: 1.13291 Size: -0.05
2019-02-12, TRADE CLOSED 14901 by 14903, Gross PnL=15.26
2019-02-12, Order Canceled/Margin/Rejected: 14902, Status: Canceled
2019-02-12, BUY EXECUTED 14904 Price: 1.13385 Size: 0.03